name: ci

on:
  push:
    branches: [master,develop]

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache-dependency-path: go.sum
      - name: Test
        run: go test -v ./pkg/models/...

  docker:
    needs: ["test-go"]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - file: Dockerfile
            type: web
          - file: Dockerfile.updater
            type: updater

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/gentoo/soko
          tags: |
            type=sha,prefix={{branch}}-${{ matrix.type }}-
            type=raw,value={{branch}}-${{ matrix.type }}-latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
